### PR TITLE
Add relevant content to meta tags #70

### LINKED ISSUE #70: Add Open Graph Tags Preview Image, Title, and Description for shared links
Add Preview Image, Title, and Description for shared links on social (i.e. Facebook, Twitter, Linkedin, iMessage) for SMC and SJ

AC:
The homepage, listings page, and individual listings have the following previews: 

**Homepage** and **Listings Page**
Image: Hero Image
Title: [City/ County] Affordable Housing Portal
Description: Search and apply for affordable housing on the [City/ County]'s Housing Portal

**Individual Listing**
Image: Listing Image
Title: [Building Name]
Description: Apply for affordable housing at [Building Name] on the [City/County]'s Housing Portal 

image

### PR DESCRIPTION
**Pull request by jaredcwhite**
Fixes #70

### CODE REVIEW

**Comment by jacchau** [comment]
Thanks for setting up the testing environment. 

I ran it through the following preview card validators: 
Facebook: https://developers.facebook.com/tools/debug/sharing
Linkedin: https://www.linkedin.com/post-inspector/inspect/
Twitter: https://cards-dev.twitter.com/validator

The individual listing pages look good for both Facebook and Linkedin. 
**Outstanding issues:** 
1) Image tag for Homepage and Listings pages: Will the image tag be updated to the hero image when we push this to prod? It's currently set as 'https://herokuapp.com/images/test-banner.jpg '. 
2) For some reason the Twitter card isn't working https://cards-dev.twitter.com/validator and I see that you have tags specifically created for Twitter.

**Comment by jaredcwhite** [comment]
@jacchau Yeah, there's no hero image for the test group, but it should work once it's for either SJ for SMC proper. The Twitter card validation seems like it's not working since the robots.txt file is blocking it, but you can view source and look at the `twitter:` meta tags to make sure they match the Open Graph tags.

**Comment by jacchau** [comment]
Thanks @jaredcwhite for the clarification and looks good. Ready for @bk3c to merged this after his code review.

**Comment by bk3c** [comment]
I have a couple of minor comments (e.g. I'd like to see the default tags come back) but given that this is already merged I think we just need to fix them in Bloom.

**Pull request merged**
